on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - run: cargo install flip-link

    - run: rustup target add thumbv6m-none-eabi

    - name: Build
      run: cargo build --release

    - run: find target/thumbv6m-none-eabi/release

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: bin
        path: target/thumbv6m-none-eabi/release
